
#Common configurations for Enhanced Mushrooms
[common]
	#Whether the mod's food items are obtainable in survival
	food_obtainable = true
	#Whether mushroom blocks should be strippable with an axe
	strippable_mushroom_blocks = true

