#This config allows you to add or remove folders or single files as Data-/Resourcepacks
#For that simply specify the file path to the folder/file relative to your .minecraft folder
[resourcepacks]
required = [
    "global_resource_packs/",
    "global_packs/required_resources/"
]

[datapacks]
required = [
    "global_data_packs/",
    "resourcepacks/Repurposed_Structures-Buzzier_Bees.zip",
    "resourcepacks/Repurposed_Structures-Environmental.zip",
    "resourcepacks/Repurposed_Structures-Farmers_Delight_Forge.zip",
    "resourcepacks/Repurposed_Structures-Ice_and_Fire_v2.zip",
    "resourcepacks/Repurposed_Structures-Immersive_Engineering.zip",
    "resourcepacks/Repurposed_Structures-Jellyfishing.zip",
    "resourcepacks/Repurposed_Structures-Savage_And_Ravage.zip",
    "global_packs/required_datapacks/"
]

optional = [
    "optional_data_packs/",
    "global_packs/optional_datapacks/"
]