
["Allow entity spawns"]
	#Whether to spawn Gunner Drones or not
	"Spawn Gunner Drones" = true
	#Whether to spawn Lemurians or not
	"Spawn Lemurians" = true
	#Whether to spawn Stone Golems or not
	"Spawn Stone Golems" = true
	#Wheter to allow Stone Golems spawn persistence or not
	"Stone Golem spawn persistence" = false
	#Wheter to allow Stone Golems laser to knockback players or not (crash risk)
	"Stone Golem laser knockback" = false
	#Wheter to allow Lemurians to spit fireballs or not
	"Lemurian fireball" = true
	#Wheter to spawn RoR monsters in the Nether or not
	"Nether spawns" = true

["Entity spawn rates"]
	#The weight of Gunner Drones in vanilla spawn rate
	#Range: 1 ~ 100
	"Gunner Drone weight" = 1
	#The weight of Lemurians in vanilla spawn rate
	#Range: 1 ~ 100
	"Lemurian weight" = 80
	#The weight of Stone Golems in vanilla spawn rate
	#Range: 1 ~ 100
	"Stone Golem weight" = 20

["Withelisted overworld spawn biomes"]
	#Use the format "mod_ID:biome" like "minecraft:plains" or "rats:ratlantis". You can see a mod's ID by clicking the 'Mods' button on the main screen and clicking on the mod's name on the left 
	"Overworld whitelist" = ["minecraft:badlands", "minecraft:eroded_badlands", "minecraft:badlands_plateau", "minecraft:wooded_badlands_plateau", "minecraft:modified_badlands_plateau", "minecraft:modified_wooded_badlands_plateau", "minecraft:beach", "minecraft:snowy_beach", "minecraft:stone_shore", "minecraft:forest", "minecraft:flower_forest", "minecraft:birch_forest", "minecraft:birch_forest_hills", "minecraft:tall_birch_forest", "minecraft:dark_forest", "minecraft:dark_forest_hills", "minecraft:wooded_hills", "minecraft:wooded_mountains", "minecraft:desert", "minecraft:desert_lakes", "minecraft:desert_hills", "minecraft:mountains", "minecraft:mountain_edge", "minecraft:gravelly_mountains", "minecraft:modified_gravelly_mountains", "minecraft:snowy_mountains", "minecraft:jungle", "minecraft:jungle_edge", "minecraft:jungle_hills", "minecraft:modified_jungle", "minecraft:bamboo_jungle", "minecraft:bamboo_jungle_hills", "minecraft:modified_jungle_edge", "minecraft:plains", "minecraft:sunflower_plains", "minecraft:river", "minecraft:frozen_river", "minecraft:savanna", "minecraft:savanna_plateau", "minecraft:shattered_savanna", "minecraft:shattered_savanna_plateau", "minecraft:swamp", "minecraft:swamp_hills", "minecraft:taiga", "minecraft:taiga_hills", "minecraft:taiga_mountains", "minecraft:giant_tree_taiga", "minecraft:giant_tree_taiga_hills", "minecraft:giant_spruce_taiga", "minecraft:giant_spruce_taiga_hills", "minecraft:snowy_taiga", "minecraft:snowy_taiga_hills", "minecraft:snowy_taiga_mountains", "minecraft:snowy_tundra", "minecraft:ice_spikes"]

["Withelisted nether spawn biomes"]
	#Use the format like "minecraft:nether_wastes" 
	"Nether whitelist " = ["minecraft:basalt_deltas", "minecraft:crimson_forest", "minecraft:nether_wastes", "minecraft:warped_forest"]

["Item settings"]
	#The Infusion max health cap
	#Range: 20 ~ 200
	"Infusion cap" = 60

["Sound settings"]
	#Wheter to allow RoR sounds or not
	"Allow RoR sounds" = true

