
[Compatibility]

	[Compatibility.vampirism]
		enable_compat_vampirism = true
		disable_integrations_version_check = false

	[Compatibility.bloodmagic]
		enable_compat_bloodmagic = true

	[Compatibility.tconstruct]
		enable_compat_tconstruct = true

