#Preferences for outputs from tags used in automatic compat in recipes
tagPreferences = ["emendatusenigmatica", "minecraft", "create", "createaddition", "thermal", "immersiveengineering", "jaopca", "botania", "quark", "tconstruct"]

