#List of curio slot type settings
[[curiosSettings]]
  identifier = "ring"
  override = true
  size = 4
[[curiosSettings]]
  identifier = "charm"
  override = true
  size = 2
[[curiosSettings]]
  identifier = "belt"
  size = 3
  override = true
[[curiosSettings]]
  identifier = "body"
  size = 2
  override = true
[[curiosSettings]]
  identifier = "back"
  size = 2
  override = true
[[curiosSettings]]
  identifier = "head"
  size = 1
  override = true
[[curiosSettings]]
  identifier = "necklace"
  size = 2
  override = true
[[curiosSettings]]
  identifier = "toad_eye_holder"
  size = 1
  override = true





